project: 
  type: website
  output-dir: docs
  
website: 
  title: "STAT 515 - Website"
  navbar: 
    left: 
      - index.qmd
      - Introduction.qmd
      - about.qmd
      
format: 
  html: 
    theme: cosmo